### ISSUE TITLE
Set up Prayer Request emails to go to Jane Hanley

### ISSUE THREAD

**Issue by BigActual** [Good-Shepherd-Catholic-Radio/Theme-2017#100]
jchanley0522@gmail.com

**Comment by d4mation** [comment]
All set. This is something they should have the ability to change on their own as needed.

https://goodshepherdcatholicradio.org/wp-admin/admin.php?page=gf_edit_forms&view=settings&subview=notification&id=2&nid=593f6cb239b5e
