### ISSUE TITLE
On-Air Personalities - Adjust Recommended Size

### ISSUE THREAD

**Issue by BigActual** [Good-Shepherd-Catholic-Radio/Theme-2017#102]
Please adjust the Profile Image recommended size to 472* 472. Most already are and I'm converting or adding new ones that size.

![image](https://user-images.githubusercontent.com/7770631/36734255-f5b5048c-1ba0-11e8-8079-1974d63eca7e.png)

**Comment by d4mation** [comment]
This issue was moved to Good-Shepherd-Catholic-Radio/cpt-on-air-personalities#1

**Comment by d4mation** [comment]
Actually, in this case, you were right. The code for this is in the theme. My bad.
