### ISSUE TITLE
Word On Fire dropped from list of Programs

### ISSUE THREAD

**Issue by BigActual** [Good-Shepherd-Catholic-Radio/Theme-2017#105]
I updated the featured image and the show dropped from the list shown on the home page and at: https://goodshepherdcatholicradio.org/radio-show-programs/

I tried adjusting the setting in the program and purging the caches; local and server.

**Comment by d4mation** [comment]
Thanks for pointing this out! This was a bug caused by moving them to the newer versions of RBM FH and the Theme making some assumptions that are only true with the Legacy version. I've adjusted this and it will no longer be an issue.
