### ISSUE TITLE
Authorize.net and PayPal checkout options enabled

### ISSUE THREAD

**Issue by BigActual** [Good-Shepherd-Catholic-Radio/Theme-2017#12]
Harry and I discussed making both credit card via Authorize.net and PayPal checkout workflows available.

**Comment by d4mation** [comment]
The Authorize.net gateway will need to be purchased. I also need an email address to use for the PayPal payments. Otherwise PayPal is good to go.

https://givewp.com/addons/authorize-net-gateway/

**Comment by d4mation** [comment]
Still need the Authorize.net Payment Gateway for this Issue.

**Comment by BigActual** [comment]
Entered the email for PayPal. Have requested Authorize.net info from Marc.

**Comment by d4mation** [comment]
@BigActual We will need the plugin and any credentials necessary.
