### ISSUE TITLE
Broken links on site need to be repaired

### ISSUE THREAD

**Issue by joelyoder** [Good-Shepherd-Catholic-Radio/Theme-2017#123]
Marc,
As part of our service, we are now finding and reporting broken links so that you can proactively fix or deal with them. Here is what we found on https://goodshepherdcatholicradio.org/

[Link Monitor Good Shepherd Catholic Radio.xlsx](https://github.com/Good-Shepherd-Catholic-Radio/Theme-2017/files/6556675/Link.Monitor.Good.Shepherd.Catholic.Radio.xlsx)

Let me know if you have any questions about these.

Thanks for your help,
Joel Yoder

**Comment by joelyoder** [comment]
Hi @hshill-gscr,
Here's an updated list of broken links. It's just a couple links so it shouldn't take long to fix.
[Link Monitor Good Shepherd Catholic Radio.xlsx](https://github.com/Good-Shepherd-Catholic-Radio/Theme-2017/files/6735535/Link.Monitor.Good.Shepherd.Catholic.Radio.xlsx)

Thanks!

**Comment by hshill-gscr** [comment]
I'm not getting a 404 on https://www.catholic.org/prayers/novenas/
Starting page: https://goodshepherdcatholicradio.org/novenas-chaplets-devotions/
Link: Novenas 
They have a lot of stuff on the page.  Perhaps an add or picture got the 404 when tested.

Fixed the second one, Legacy.com seems to change their file structure every two months.

Marc A Wysocki signing in as webmaster@gscr.org

**Comment by joelyoder** [comment]
There's nothing wrong with that link, so I've set our system to ignore the false-positive on it. Marking this complete since all of the other broken links are fixed.
