### ISSUE TITLE
In Screen Sizes above Phablet, the Player should be fixed in the Header

### ISSUE THREAD

**Issue by BigActual** [Good-Shepherd-Catholic-Radio/Theme-2017#14]
In screen sizes for tablet and above, the player is to cease existing as a bar at the bottom of the screen and become a button on the top right of the screen, above the phone number and social icons.  About 56 px high and as wide as it needs to be to fit the play/pause button, The text "Listen Live", and the speaker icons/volume bar

**Comment by d4mation** [comment]
@BigActual and I deliberated back and forth with mocks to make this happen and we landed on this. It seems to accomplish this in the best way without overcrowding things.

![image](https://user-images.githubusercontent.com/7770631/28090242-aab86160-6659-11e7-96f8-64ec1f03ccec.png)
