### ISSUE TITLE
Create and implement a "Become an Underwriter" Form

### ISSUE THREAD

**Issue by BigActual** [Good-Shepherd-Catholic-Radio/Theme-2017#19]

**Comment by BigActual** [comment]
Form is present but requires proofing by Eric

**Comment by BigActual** [comment]
This needs to be implemented on the site.

**Comment by d4mation** [comment]
> Steve Bennett [3:40 PM] 
> While I figure that out, do you have any ideas for how to incorporate the Become an Underwriter form? We forgot to do that.
> 
> Eric Defore [3:40 PM] 
> Aside from doing something like 1/3 + 2/3 columns, I’ve got nothing
> 
> Eric Defore [3:41] 
> Does the form _need_ to be on the home page? It almost seems more appropriate to have it on its own page or on the Underwriters page.

**Comment by d4mation** [comment]
To me, it seems like if you wanted to become an Underwriter, it is something you'd be looking for specifically. Whereas, the Home Page should be more geared toward the "general" visitor who may just be looking for things like Donations/Prayer Requests/Currently Playing Show/etc.

**Comment by BigActual** [comment]
Thinking globally about this, forms are overlays on the home page. There's no reason to change that workflow on sub-pages. So, let's ensure that all forms become overlays.

I agree that the become an underwriter form does not need to be on the home page.

**Comment by d4mation** [comment]
I was thinking the same, actually. I'll either find a way to wrap all Gravity Form Shortcodes in the overlay, or I'll make my own wrapping shortcode to place it within one.

**Comment by d4mation** [comment]
Just added it to the Underwriters Page using a new Shortcode I whipped up. You can see it here: http://goodshepradio.wpengine.com/underwriters/

All it does it allow you to create a Button which will then open an Overlay containing the desired Form. I placed it in-line with the copy, but feel free to move it however you'd like.

In the WYSIWYG there is a button to help generate that Shortcode as well.

**Comment by BigActual** [comment]
![image](https://user-images.githubusercontent.com/8271108/30292081-c4830d6e-9702-11e7-871b-5f92e14751cf.png)

**Comment by d4mation** [comment]
Adjusted some CSS and converted that description to an `<ol>` for you. Seems to be working well now.

![image](https://user-images.githubusercontent.com/7770631/30292590-c410ec14-9704-11e7-8fc1-2ce21b1d3fef.png)

**Comment by BigActual** [comment]
Nice modification. Glad it was easy to implement.
