### ISSUE TITLE
Rework Footer

### ISSUE THREAD

**Issue by BigActual** [Good-Shepherd-Catholic-Radio/Theme-2017#20]
MI Catholic Radio
Catholic Radio Travel Guide
No Map, but otherwise a combination of Holy Family Website and Barraga Website

**Comment by d4mation** [comment]
#21 and #22 are likely prerequisites for this.

**Comment by BigActual** [comment]
The content is all present but it requires styling.
Let's take it to three vertical columns which will consist of the email subscription, the text column, and the Give form. 
Underneath that, let's align the three affiliation logos from left to right and center justify them. There will be more as time goes on so adding a logo should not be hard for staff.
