### ISSUE TITLE
Add MI Catholic Radio to Resources Page

### ISSUE THREAD

**Issue by BigActual** [Good-Shepherd-Catholic-Radio/Theme-2017#22]

**Comment by d4mation** [comment]
Is this an external link? Also, where is the "Resources" Page to go? I don't know if one exists currently.

**Comment by d4mation** [comment]
We currently have a separate Resources Page, but I'm not sure what to do with it for this Issue and #21.

http://gscr.realbigwebsites.com/resources/

**Comment by BigActual** [comment]
Added
