### ISSUE TITLE
Dave Krajewski Information and Archive

### ISSUE THREAD

**Issue by BigActual** [Good-Shepherd-Catholic-Radio/Theme-2017#24]
Dave's show will be on the air for a bit longer. An archive of shows needs to go online relatively soon. This refers directly to #23

**Comment by d4mation** [comment]
This is pending all the API information from Ave Maria.

**Comment by BigActual** [comment]
Actually, Dave is a local host. He's quite ill with Cancer so this page is specific. It's important to the client that Dave's page be ready to go on launch because his shows will become a memorial to his work.

**Comment by d4mation** [comment]
Do they have any way for us to pull in an archive? We're going to need a database to pull in show descriptions/audio/etc. unless we want to input the entire archive manually.

**Comment by BigActual** [comment]
I asked Marc if he's created anything. Likely no. I'll go to Dan and Harry if he has not created anything.

**Comment by BigActual** [comment]
http://www.gscr.org/wordpress/blue-collar-theology/

**Comment by BigActual** [comment]
I've created both a blank page for Dave and a blank page for his show. I've connected the two together, but have not content. Will ask Harry for additional input.

**Comment by BigActual** [comment]
I've asked Harry for a photo. He's trying. Marc has provided the link to the repo of shows. How does this one stand on your end @d4mation ?

**Comment by d4mation** [comment]
Haven't been able to get to this at all. Been a busy week. I still need to download all the audio files and/or we need to find a 3rd party service (like SoundCloud or something) to host them for us to embed them.

**Comment by d4mation** [comment]
If we want a _true_ archive for his Show, we will need an entry for each past show we have information/audio for. Right now there's just an entry for this past Wednesday.

I guess we'll need to know which dates all the audio files from your link above match up with and then create them accordingly.

http://gscr.realbigwebsites.com/on-air-personality/dave-krajewski/

**Comment by d4mation** [comment]
This link appears to have more audio files for us to pull in.

Like I said, we will need dates and time slots for each of them so we know which one is associated with which. Then we can have a proper Archive output on his On-Air Personality page.

http://www.gscr.org/audio/Blue_Collar_Theology_Uploads/

**Comment by BigActual** [comment]
I've asked for clarification on the dates from Marc.

**Comment by BigActual** [comment]
as a stop gap, just assume each one is a week older than the one before.

**Comment by BigActual** [comment]
Is this finished?

**Comment by d4mation** [comment]
Yes, all the provided audio for Dave Krajewski has been added as past Radio Shows with a SoundCloud player attached to each for playback.

**Comment by BigActual** [comment]
Great thanks.
