### ISSUE TITLE
Verify that there is no page load issue with "Christ is the Answer with Father Jim Ricardo"

### ISSUE THREAD

**Issue by BigActual** [Good-Shepherd-Catholic-Radio/Theme-2017#26]
This was given to me in the meeting with Harry. Symptom not described to us by the end user.

**Comment by d4mation** [comment]
Likely related to #28.

**Comment by d4mation** [comment]
#28 seems fixed now, so we'll need to have this looked into again. 

I know I can click to enter Radio Show/Event single templates just fine. It was only the main Calendar that would give me problems before.

**Comment by d4mation** [comment]
Need confirmation whether this is still broken or not. Could not replicate.

**Comment by BigActual** [comment]
I'm with you that this was directly related to #28. Also, they have no caching in place on a dev server. This is likely taken care of but let's leave open until the client signs off after the launch.
