### ISSUE TITLE
Use more Rose and Gold throughout the design

### ISSUE THREAD

**Issue by BigActual** [Good-Shepherd-Catholic-Radio/Theme-2017#31]
The site is too purple. We need to find more balance with other colors used in Catholic life; Rose and Gold

**Comment by d4mation** [comment]
Do you have any suggestions as to where this should go? We had talked about this before and we landed on there weren't any good places really. Right now gold is being used for active links in the Navigation and I think somewhere else.

**Comment by d4mation** [comment]
We've done a lot of back and forth with this trying different color combinations throughout the site and nothing seemed to work nicely at all. The purple with green accents and the occasional gold seems to work best&mdash;forcing more colors in has proven difficult.

Unless we have specific suggestions, I think this Issue should be closed.

**Comment by BigActual** [comment]
Well, we're still putzing with this, so let's carry on with our conversation here.

**Comment by BigActual** [comment]
Can you please make the drop-downs white text on watermelon, I mean Rose, in the default state and on hover make the background lighten up to like 80%?

**Comment by d4mation** [comment]
Changed the dropdowns to those colors. They still have white borders (and a white triangle) on the top.

**Comment by BigActual** [comment]
Looks like it's purple instead of rose?

**Comment by BigActual** [comment]
Rose in the default state, 80 % rose on hover

**Comment by d4mation** [comment]
Ah, since you said "watermelon" I figured you meant Purple since that's the new "Purple" color. Rose is a separate, until now unused, color in the Theme.

Swapped out the Menu Colors for Rose. Now it looks extra 🍉-y

**Comment by BigActual** [comment]
Approved

**Comment by d4mation** [comment]
:tada: :tada: :tada:
