### ISSUE TITLE
Adoration Chapel photograph added to prayer request

### ISSUE THREAD

**Issue by BigActual** [Good-Shepherd-Catholic-Radio/Theme-2017#46]

**Comment by d4mation** [comment]
Are there any changes that need to be made to that section for this?

Right now there's another picture in place on the left-hand side of the section. The right-hand side has a button that opens the modal for submitting the form.

**Comment by BigActual** [comment]
Hold off on this for the moment. I'll update this entry with a picture. I took a bunch and they're all great, except for the ones that go with this section. 

Potentially add this photograph, if it can be used to support the end user's workflow or reinforce the message. The existing diagram is a winner. No one dislikes the current copy. It needs to be built out and balanced though as distribution of elements within the container is clunky
  - balance, white space, button placement
Need to add copy that describes what happens on submit
  - 'Good Shepherd sits adjacent to the Saint Joseph Adoration Chapel manned 24 hours a day with volunteers who lift up the requests of our Parishioners. Submit your prayer request for the team here.'
Play with the balance of the elements and the placement of the submit button to achieve a more cohesive presentation.

**Comment by BigActual** [comment]
Ok, let's make it look something like this: My spacing may be off, fonts are wrong, the button is badly represented. This is mostly to show the placement of elements you already have correct.
![image](https://user-images.githubusercontent.com/8271108/30095070-274a8c42-929e-11e7-9594-e6e0d8aab74e.png)

**Comment by BigActual** [comment]
Updated copy as follows: 

> Good Shepherd Catholic Radio offices are adjacent to the Adoration Chapel of St Joseph the Worker Oratory in Jackson. All prayer requests submitted to Good Shepherd Catholic Radio are placed in the prayer request basket and entered in prayer by the volunteers in attendance with the Holy Host every hour of every day all through the year.

**Comment by d4mation** [comment]
So the Form is going to exist within the section instead of within a Modal now?

**Comment by d4mation** [comment]
![image](https://user-images.githubusercontent.com/7770631/30123560-760a0bde-9300-11e7-93ef-40d34a6d43ae.png)

**Comment by d4mation** [comment]
I guessed on the level of transparency for the white backdrop. It is set to 40% opacity right now.

**Comment by BigActual** [comment]
Approved
