### ISSUE TITLE
Underwriters page is showing the items too large

### ISSUE THREAD

**Issue by BigActual** [Good-Shepherd-Catholic-Radio/Theme-2017#47]

**Comment by d4mation** [comment]
How are we wanting this to change?

**Comment by BigActual** [comment]
Add the category field into the CPT so we can eventually separate the display of Underwriters by the type of industry they are in.
Add the Excerpt Field into the CPT and/or default the number of characters displayed in the description on the page. Maybe a hundred characters and show a read more tag
Create separate meta fields for Address and phone
In the template:
Standardize the default height of the listing so they are all the same
Standardize the logo (Generous white space)
Decrease the title of the company font size. It's overbearing.
Increase the margins a bit to add more white space between listings
Create an alternating color grid behind the listing - First listing white background, second listing Gold with a white overlay so everything is legible above it, Keep Switching back and forth.


In the template, let's

**Comment by d4mation** [comment]
> Add the Excerpt Field into the CPT and/or default the number of characters displayed in the description on the page.

Currently, the Underwriters don't have a Single page. Clicking one goes straight to their website. This would need to change if we were to implement an Excerpt.

**Comment by BigActual** [comment]
- [ ] Accordion for description

**Comment by d4mation** [comment]
> Standardize the default height of the listing so they are all the same

Even if we limit to 100 characters for each listing, this isn't 100% possible. This is because we aren't using a monospace font so each character has a different width, meaning there could be more or less line breaks per listing. Especially if a listing were to have only 10 characters or something else small for some reason.

What I can do is use JavaScript to calculate the height of the largest item and then apply that height to each one, either globally or per-row. However, that could look silly in cases where they may be an incredibly short listing being given a massive height.

This would overall give the desired effect of them having a standard height. It may just apply _slightly_ after page load and cause a noticeable jump in the content.

**Comment by BigActual** [comment]
Can you limit the max height of the container?

**Comment by d4mation** [comment]
I could, but that wouldn't have the desired results I don't think. What I'd need to do is instead of utilizing an excerpt, instead output the full content and hide x% of it. Then expand to show the full content when the accordion is toggled. In this case, I could set a max-height where at a certain point, it blurs out the rest.

Something like this: https://css-tricks.com/examples/ReadMoreFade/

**Comment by d4mation** [comment]
> Decrease the title of the company font size. It's overbearing.

Right now they are sized to be `<h3>`. It actually makes them smaller than most of the logos. Should they be smaller still?

![image](https://user-images.githubusercontent.com/7770631/30136228-f699bb52-932b-11e7-8b86-23f675860794.png)

**Comment by d4mation** [comment]
> Create an alternating color grid behind the listing - First listing white background, second listing Gold with a white overlay so everything is legible above it, Keep Switching back and forth.

Right now this may not look so great as it is 2 per row. So it will be one big column of white and one big column of gold.

Maybe it should instead be per-Row? So a white Row then a gold Row?

**Comment by d4mation** [comment]
> Decrease the title of the company font size. It's overbearing.

Oh, wait, do you mean this? I'd just have to ensure that any headings used within the copy of an Underwriter get shrunk down to maybe `<h6>` size.

![image](https://user-images.githubusercontent.com/7770631/30136809-abed52d2-932e-11e7-9e78-b85015c174b3.png)

**Comment by d4mation** [comment]
Current iteration is live at: http://gscr.realbigwebsites.com/underwriters/

Only things not complete I've asked questions about above.

**Comment by BigActual** [comment]
Sure, My thoughts on your above questions:

- [ ] Hide a bit less so just a line of copy more will show per listing
- [ ] Yes, you touched on this twice above, Those titles are taking up too much space
![image](https://user-images.githubusercontent.com/8271108/30141750-498c2704-934b-11e7-8b87-c2a4116b3cbd.png)
Those are three examples where the titles are taking up enough space that the content isn't visible. That content is the tease that gets users to interact. 

- [ ] ALternating rows will make it look like both items in a row are together, It's the same problem you identified above for the columns, just going the other way. We either need to move to three on a row or find a way to have it alternate back and forth, but be able to switch up on smaller screens where they start to stack in a single column. My vote may be to just switch to three in a row.

**Comment by BigActual** [comment]
Though you'd have to switch from three columns to one column when programming the responsive part of this, and never have an even number of Underwriters on a row.

**Comment by d4mation** [comment]
> Yes, you touched on this twice above, Those titles are taking up too much space

Yeah, the first time I was thinking in the case of Miller's Shoes where instead of a Logo, they just have a text link. But you were actually talking about how for a few of the listings, they have headers _in their content_ which are showing as very large. I'll have to correct that.

**Comment by d4mation** [comment]
New iteration has been pushed: http://gscr.realbigwebsites.com/underwriters/

I'm not sure how I feel about the alternating backgrounds. It is an alright idea, but I don't think it works here.

**Comment by BigActual** [comment]
Yeah, that's awful painful to look at. How about three across w/o the colors though.

**Comment by d4mation** [comment]
Just removed the background colors

**Comment by BigActual** [comment]
Post launch, I want to take these items and create relevant fields for address, phone, website, and the description. On the front end, standardize the display of these fields in a consistent manner.

**Comment by BigActual** [comment]
Client approved for initial launch.
