### ISSUE TITLE
Remove color behind affiliates

### ISSUE THREAD

**Issue by BigActual** [Good-Shepherd-Catholic-Radio/Theme-2017#48]

**Comment by d4mation** [comment]
To be clear, you mean the background color behind all the Affiliate images?

![image](https://user-images.githubusercontent.com/7770631/28538978-0bd60302-707e-11e7-8021-293098fef0ac.png)

Knocking that out to white might look a little strange as the Social Media Icons and the Copyright info is set to be on the Purple background right now. The Social Media and Copyright could be moved to a white background as well, I'm just trying to think it through.

**Comment by BigActual** [comment]
Sure, I'd say go all white down there.
