### ISSUE TITLE
Make all Menu Items All Caps

### ISSUE THREAD

**Issue by BigActual** [Good-Shepherd-Catholic-Radio/Theme-2017#50]

**Comment by d4mation** [comment]
Just at the Top-Level? Or for all dropdowns as well?

**Comment by BigActual** [comment]
All

**Comment by BigActual** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/10211715-283868566_2-s4-v1.png?transparent=1&palette=1&width=50)
