### ISSUE TITLE
Adjust green bar On Hover element

### ISSUE THREAD

**Issue by BigActual** [Good-Shepherd-Catholic-Radio/Theme-2017#51]
From .5em to .25 em

**Comment by BigActual** [comment]
Can you slow down the speed of the line growth?

**Comment by d4mation** [comment]
It currently takes 200ms to go from left to right. How much slower should it go?

**Comment by BigActual** [comment]
try 500

**Comment by d4mation** [comment]
Adjusted to 500ms

**Comment by BigActual** [comment]
600

**Comment by d4mation** [comment]
Now at 600ms

**Comment by BigActual** [comment]
Good. I like the way the delay provides additional time to focus on each element as it's hovered over.
