### ISSUE TITLE
Hover effect on the blog section of the home page

### ISSUE THREAD

**Issue by BigActual** [Good-Shepherd-Catholic-Radio/Theme-2017#54]
make consistent with Hero area and On Air Personalities

**Comment by d4mation** [comment]
Ditch the green overlay and instead place a green line just below the blog titles?

![image](https://user-images.githubusercontent.com/7770631/29790447-e90c2c2a-8c07-11e7-8e7f-cdc2d7699d1e.png)

**Comment by BigActual** [comment]
yes, and move the overlay to the bottom of the container

**Comment by d4mation** [comment]
Should it still use the fade effect to the right? I don't think it works as well here due to the larger titles.

![image](https://user-images.githubusercontent.com/7770631/29826313-ee04f836-8ca4-11e7-84f9-db07988a1db8.png)

**Comment by BigActual** [comment]
Yes, make it consistent.

**Comment by d4mation** [comment]
So, keep the fade on the right-hand side? If so, this is done.
