### ISSUE TITLE
Adjust positioning of Support GSCR and Listening Options Buttons

### ISSUE THREAD

**Issue by d4mation** [Good-Shepherd-Catholic-Radio/Theme-2017#56]
@bigactual 
> In the containers for Support GSCR and Listening Options, would you please drop those buttons down so they sit just up off the bottom of the containers. Look to the boxes to the left and adjust the buttons up and down until they sit nicely in line with the copy in the overlays.

**Comment by BigActual** [comment]
Something more like this: (Solely for placement, ignore the gaping white holes this created in the container)
![image](https://user-images.githubusercontent.com/8271108/29790969-64192f84-8c09-11e7-8de7-7cd23c55e6eb.png)

**Comment by BigActual** [comment]
Nice
