### ISSUE TITLE
Adjust Footer Widgets 

### ISSUE THREAD

**Issue by d4mation** [Good-Shepherd-Catholic-Radio/Theme-2017#57]
@bigactual
> Could you either make the widget containers smaller or increase the spacing/margins on the three footer widgets (Donate, Location/Organization, and Join Our Email List until the word non-profit is driven down a line?

I can adjust the width of each and adjust the padding between them for spacing, but they may end up looking a bit funny and narrow that way.

Probably the best way to bump that down is by bumping up the font-size slightly in that section. 

However, this _is assuming_ that the User hasn't adjusted their browser font size. This will be based on a font-size of `16px` (the default). If they've zoomed in or adjusted font sizes their screen will look very different no matter what adjustments we make here.

**Comment by BigActual** [comment]
I understand but it's a minor change that makes a positive impact on the spacing. Let's go ahead and adjust the padding-left and padding-right on div class small-12 medium-4 columns from 15 to 25.

**Comment by d4mation** [comment]
Adjusted to `1.5625rem` which at a `16px` font size calculates to `25px`

**Comment by BigActual** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/10220507-283868566_2-s4-v1.png?transparent=1&palette=1&width=60
)
