### ISSUE TITLE
Add ability to change pictures to Events section on the home page.

### ISSUE THREAD

**Issue by BigActual** [Good-Shepherd-Catholic-Radio/Theme-2017#61]
Leave colors in place and add the ability to change from a color to a picture. The pictures here will change by the season or if a specific main event is coming up.

**Comment by BigActual** [comment]
Whatever picture goes up here could also bet he hero image for the page /events/ 
It would sit flush against the menu as images do on other sub pages which would push the calendar down.

**Comment by d4mation** [comment]
> Whatever picture goes up here could also bet he hero image for the page /events/

This will be more challenging as that is not a Page. That is an archive for a template that is created by The Events Calendar. I'll have to see what kind of hooks I have access to inject into that template with, as I'd rather not straight-up override it as that could cause problems down the line as the plugin updates.

**Comment by d4mation** [comment]
Background image is re-added. There's technically one in place now since I'm using the same values as before and it was never cleared out when we removed it from the code.

**Comment by BigActual** [comment]
Thanks

**Comment by d4mation** [comment]
Home Page Events background image is now also used as a Hero Image on the Calendar. It is only used if you're _not_ viewing the Radio Shows category; which, with the addition of the Radio Shows List page, probably shouldn't happen anymore anyhow.

![image](https://user-images.githubusercontent.com/7770631/29925274-cab226c6-8e2d-11e7-96f4-50afea285937.png)
