### ISSUE TITLE
Wordpress Admin Bar Glitch

### ISSUE THREAD

**Issue by BigActual** [Good-Shepherd-Catholic-Radio/Theme-2017#64]
I've noticed a glitch. It's pretty consistent, regardless of CPT type. If you go to any cpt from the home page, and look at the WordPress admin bar at the top, it will read Edit Page instead of reading Edit [CPT Name]. If you refresh the page, the link changes to the appropriate CPT. If, after loading the correct CPT link, from a refresh, one goes back using the back button, the CPT link sticks in the admin bar until you refresh. Even if you then go to another CPT, the last CPT menu item sticks. until the page is refreshed. Any Ideas?

![image](https://user-images.githubusercontent.com/8271108/29833156-777e21d8-8cb8-11e7-80ad-f646ab95f2f8.png)

**Comment by d4mation** [comment]
Thankfully, this turned out to be easy and doesn't seem to have any adverse effects 😌

**Comment by BigActual** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/10134284-283868566_2-s4-v1.png?transparent=1&palette=1&width=50)
