### ISSUE TITLE
Search Tool adjustments for Radio Shows

### ISSUE THREAD

**Issue by BigActual** [Good-Shepherd-Catholic-Radio/Theme-2017#65]
http://gscr.realbigwebsites.com/events/category/radio-show/
- [ ] 'EVENTS IN' provides no results
- [x] NEAR (Lociation seems irrelevant please remove
- [x] VIEW AS seems to do nothing. Can we make it work with only relelvant list types; list, month, week, day?

**Comment by d4mation** [comment]
`EVENTS IN` it technically does work, but only on a HARD Refresh (Not allowing The Events Calendar to do its thing) and it only works for 2 months out (We limited creation of the Recurring Events to 2 months to slim down the database). I'll have to see if I can get this working. It is probably some odd quirk with the filtering code I have in place for Events vs. Radio Shows.

I've got the other two taken care of

**Comment by BigActual** [comment]
Can you change the word it to SHOWS IN

**Comment by BigActual** [comment]
and only show the next two months then?

**Comment by BigActual** [comment]
Actually, I'm thinkiing this is really a useless tool set for radio shows. Shows in a month seems totally irrelevant as compared to real calendar events.

**Comment by BigActual** [comment]
Yeah, ditch it all together for radio shows. It seems like a distraction.

**Comment by d4mation** [comment]
Yeah, overall I think the Week View is the most useful, and we already have that in the form of http://gscr.realbigwebsites.com/radio-show-schedule/. 

My original intent was for the dedicated Schedule page to be used as I had a lot of problems getting the Calendar view working even to the point it is at now.

**Comment by d4mation** [comment]
https://github.com/Good-Shepherd-Catholic-Radio/Theme-2017/issues/28#issuecomment-313254822

> Given the existence of the Schedule page, I'm not sure why a link to the Radio Shows Category page exists in the Navigation. It should/could be removed.

**Comment by BigActual** [comment]
It seems to me that the first submenu is really logical and self-explanatory; Schedule.
However, The second submenu, Programs, should go to an alphabetical list. There is a list view available. Let's change the default view to that and style the list view out.

**Comment by BigActual** [comment]
I see you brought up #28. 
It's a pretty common occurrence, apparently, for an End User to want to look at the list of all shows, It's a common resource on sister sites like Ave Maria.

**Comment by d4mation** [comment]
I guess that's what's confusing to me though. The Radio Show Schedule page _is_ a list of all shows. At least for that current week. If any changes are made to the schedule, that page automatically updates.

**Comment by d4mation** [comment]
> Let's change the default view to that and style the list view out.

I've been playing around with the code and I think if we wanted to do this, our only option would be to make it so that the Radio Shows can _only_ use List View. This is because we're using one CPT as if it were 2 to accommodate Reccurring Radio Shows and I have no way of telling it "Events use Month as the Default, but Radio Shows use List as the Default" due to some hacky programming on the part of The Events Calendar. Instead of just grabbing a default value using a Filter (Which it should, because then I could override it how we need to), it instead has a hardcoded assumption to always, _always_ use the value **stored** as the Default, which is Month.

**Comment by BigActual** [comment]
Let's blow out their interface then and list the shows out alphabetically. Keep a search tool in place though

**Comment by BigActual** [comment]
Eric, it occurred to me that my last statement could be misinterpreted. I'm only referring to this page when I say blow out their interface. The other page /events/category/radio-show/ is fine

**Comment by d4mation** [comment]
So, remove the List view but otherwise leave the Calendar version intact?

I don't believe I can replace their List view with our own. I can only make a separate page with our own List view.

**Comment by BigActual** [comment]
The calendar version on page /events/coategory/radio-show is good, so stet
Sure, feel free to replace the page and make your own. Just want to be able to search for a specific show at the top o the page.

**Comment by d4mation** [comment]
That's not quite what I mean. At least if I'm understanding you correctly.

If we want to use our own List view, it will need to be a completely separate page. Similar to the Radio Show Schedule page. It would exist elsewhere on the site.

**Comment by BigActual** [comment]
Yes, we're saying the same thing.

**Comment by d4mation** [comment]
I've got a new Search/List page built out locally. Just having some difficulty having each Radio Show display all the Time Slots it occupies. The Events Calendar is storing it in a silly way that I have to convert into a proper Time Stamp

**Comment by d4mation** [comment]
Actually, turned out it was more likely that maybe some Radio Shows were created before a Time Zone was set? I gave re-saving the Radio Show and it corrected the output for the time.

I'm trying to get this Live now, but it is not showing up as a template I can select 😐

**Comment by d4mation** [comment]
Typing in the Search Box automatically filters it down without requiring a page refresh.

The "Edit this Radio Show" link only shows if you're logged in (and have the permissions to Edit it) and is there just for convenience if it were to need edited.

![image](https://user-images.githubusercontent.com/7770631/29894374-1a63ff0e-8da3-11e7-87a1-7402c24ae3aa.png)

**Comment by d4mation** [comment]
http://gscr.realbigwebsites.com/radio-shows-list/
