### ISSUE TITLE
Sheduled Items Single Layout Modifications

### ISSUE THREAD

**Issue by BigActual** [Good-Shepherd-Catholic-Radio/Theme-2017#67]
- [x] Move Featured Image up and under the Page Title
- [x] Switch the font size of the Page title H1.tribe-events-single-event-title and the date and time info span.tribe-event-date-start to 1.7em
- [x] Move the breadcrumbs to just below the image
- [x] Verify with me the need to keep the (See all) link. What purpose does it serve?
- [x] Change the color and shape of the buttons to match the theme for + GOOGLE CALENDAR and the + ICAL EXPORT buttons

**Comment by d4mation** [comment]
> Verify with me the need to keep the (See all) link. What purpose does it serve?

It links to a List View of every occurrence of that Radio Show. 

Example: http://gscr.realbigwebsites.com/radio-show/catholic-connection-with-teresa-tomeo-live/all/

**Comment by BigActual** [comment]
Right, I saw that too. I just don't see a need for that information. Do you?

**Comment by d4mation** [comment]
> Move Featured Image up and under the Page Title

I figure in this case, we shouldn't bother with showing the default Microphone image, right?

![image](https://user-images.githubusercontent.com/7770631/29884350-3cc32b3c-8d81-11e7-9abd-1d89515c22a5.png)

**Comment by d4mation** [comment]
> Change the color and shape of the buttons to match the theme for + GOOGLE CALENDAR and the + ICAL EXPORT buttons

They actually are already colored that way, but it is some kind of specificity issue where since I'm including Events Calendar's CSS after my own it is getting overridden _only_ if you AJAX load to it from somewhere like the Home Page. If you Hard-Refresh the page while viewing a Single Schedule Item, it works.

I'll just need to adjust the specificity for that so mine always takes effect.

**Comment by d4mation** [comment]
Example page: http://gscr.realbigwebsites.com/radio-show/the-doctor-is-in-with-dr-ray-guarendi-live/2017-08-30/

It probably needs the same treatment as #69
