### ISSUE TITLE
Buttons stopped working n Underwriters page

### ISSUE THREAD

**Issue by BigActual** [Good-Shepherd-Catholic-Radio/Theme-2017#72]

**Comment by d4mation** [comment]
The ones to expand the content downward? I haven't touched those since then. Have you tried Hard Refreshing?

![image](https://user-images.githubusercontent.com/7770631/30222668-90cf13ce-9495-11e7-9952-5aa3c3c55fe0.png)

**Comment by BigActual** [comment]
Harry and I had both lost the ability to use the button. But it does work after a hard refresh. Thanks
