### ISSUE TITLE
Post Promoter Pro causing PHP Errors on the User Edit Screen

### ISSUE THREAD

**Issue by d4mation** [Good-Shepherd-Catholic-Radio/Theme-2017#82]
This prevents the User Password from being changed unless the plugin is temporarily disabled.

@BigActual can you open a ticket for this? I don't have the credentials for this.

```
Notice: Constant PPP_LOCAL_TOKENS already defined in /nas/content/live/goodshepradio/wp-content/plugins/post-promoter-pro/includes/share-functions.php on line 154

Notice: Undefined property: PPP_Twitter_User::$twitter in /nas/content/live/goodshepradio/wp-content/plugins/post-promoter-pro/includes/libs/twitter-user.php on line 128

Fatal error: Uncaught Error: Call to a member function getRequestToken() on null in /nas/content/live/goodshepradio/wp-content/plugins/post-promoter-pro/includes/libs/twitter-user.php:128 Stack trace: #0 /nas/content/live/goodshepradio/wp-content/plugins/post-promoter-pro/includes/twitter-functions.php(721): PPP_Twitter_User->get_auth_url('http://goodshep...') #1 [internal function]: ppp_tw_profile_settings(Object(WP_User)) #2 /nas/content/live/goodshepradio/wp-includes/class-wp-hook.php(298): call_user_func_array('ppp_tw_profile_...', Array) #3 /nas/content/live/goodshepradio/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array) #4 /nas/content/live/goodshepradio/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #5 /nas/content/live/goodshepradio/wp-admin/user-edit.php(647): do_action('edit_user_profi...', Object(WP_User)) #6 {main} thrown in /nas/content/live/goodshepradio/wp-content/plugins/post-promoter-pro/includes/libs/twitter-user.php on line 128
```

**Comment by BigActual** [comment]
Will do.

**Comment by BigActual** [comment]
Tech support is on Github. I suspect that you should create the issue so that GH notifies you of follow up.

https://github.com/postpromoterpro/post-promoter-pro/issues

**Comment by d4mation** [comment]
Ah, didn't know that. I recognize that dev from EDD stuff, haha. I'll open an Issue over there.

**Comment by d4mation** [comment]
Issue opened at postpromoterpro/post-promoter-pro#261

**Comment by BigActual** [comment]
opened issue through Harry's profile (and his email address). Directly referenced the GH issue, but I'll follow up with Harry so he doesn't have to deal with it.

**Comment by d4mation** [comment]
A PR for the above Issue I opened was just closed a few hours ago and a new version was released. I'm going to confirm whether this is still a problem or not on Staging.

**Comment by d4mation** [comment]
This does seem to be fixed. However, I believe the bug was in part due to Post Promoter Pro not being configured at the time and now it is, so the bug may be impossible to hit as it is anymore anyhow.
