### ISSUE TITLE
Google Maps: MissingKeyMapError

### ISSUE THREAD

**Issue by d4mation** [Good-Shepherd-Catholic-Radio/Theme-2017#84]
Google Maps won't load since it needs an API Key.

Assigning you, @BigActual, since we may want the client to set it up themselves. If not, I can handle it.

API Key goes here:
https://goodshepherdcatholicradio.org/wp-admin/edit.php?page=tribe-common&tab=addons&post_type=tribe_events

Example of Error:
https://goodshepherdcatholicradio.org/event/jackson-family-fall-festival/

**Comment by BigActual** [comment]
Thanks. Will address this.

**Comment by d4mation** [comment]
Accidentally closed this instead of #87. Re-opened.

**Comment by ikcosyw** [comment]
Is this two issues? I clicked the link and put an API key in.  Will we need to do something different for events that users add?

**Comment by d4mation** [comment]
The other issue (#87) is unrelated to this one.

For events that visitors add, if they enter an address and showing the map is enabled, it will show a map.

When a visitor adds an event, it is added as a Draft and it needs to be approved before it gets Published, so at that time it could be reviewed to ensure that the map is enabled if necessary.
