### ISSUE TITLE
Have the Player alert User if the Stream is down

### ISSUE THREAD

**Issue by d4mation** [Good-Shepherd-Catholic-Radio/Theme-2017#93]
Right now it just kind of "resets" and does nothing. If a message appeared saying that the Stream is down it would be better.

**Comment by d4mation** [comment]
@BigActual Should be possible. We can get this set to show an alert to the User saying that the Stream is having technical difficulties and then have it email us.

http://www.jplayer.org/latest/developer-guide/#jPlayer-event-error-codes

**Comment by BigActual** [comment]
Great. Set it to email me, Harry, Marc, and Dan for now. We can reduce the number of recipients later.
