### ISSUE TITLE
Player Stops when switching pages

### ISSUE THREAD

**Issue by BigActual** [Good-Shepherd-Catholic-Radio/Theme-2017#98]
I remember a conversation about putting up the warning to the end user about how if they leave the site, the player will stop. I'm wondering if somehow that change caused the player to stop continuing to work as a user switched screens within the site. 
The player should continue to function as it used to when users switch pages in the site, without putting up the warning.

**Comment by d4mation** [comment]
Huh, you're right. It seems to be activating that on every link now. I'll figure out what's going on.
